### ISSUE TITLE
Move language repo to VitaShell

### ISSUE THREAD

**Issue by TheOfficialFloW** [xy2iii/vitashell-themes#148]
Hi guys, thanks for contributing and managing the translations. I am planning to add an option to download translations within VitaShell, for that I want to move the language files to a branch in VitaShell. Do you all agree?

**Comment by Sora3100** [comment]
Huh, funny. I asked this yesterday in IRC.

**Comment by xy2i** [comment]
No issues with it.

**Comment by ghost** [comment]
I agree.

**Comment by fox-john** [comment]
Totally agree ! ;)

**Comment by limyz** [comment]
If that's the case, this repository can be depreciated when the branch is up. I will create an issue in VitaShell regarding migration.

**Comment by xy2i** [comment]
It has been an absurdly long time, and to my surprise nobody has taken up the work of migrating this (perhaps nobody cares about translations...) [I made a post about the state of this repo here.](https://github.com/xy2iii/vitashell-themes/pull/204#issuecomment-341531313) 

At this point, I'm not really taken up by anything, so I'll take up the work of migrating these to VitaShell, then close/delete this repo forever (probably close, because I think some hyperlinks still reference here.)

**Comment by 1upus** [comment]
Sad. So sad :/

**Comment by xy2i** [comment]
Now done: https://github.com/TheOfficialFloW/VitaShell/pull/322
I realised I forgot to pull #198.. but I closed here seeing a newer version was commited already. Correct me if this is in error @1upus.

**Comment by xy2i** [comment]
Closing, this has been pulled in.
