### ISSUE TITLE
How to change font color?

### ISSUE THREAD

**Issue by Shinygati** [xy2iii/vitashell-themes#47]
Would love to have the font changed to black like in the screenshots but i'm stuck with a bright green/blue how can i change this?

**Comment by ghost** [comment]
i do not know either, i though that was with html codes but it doesn't

**Comment by xy2i** [comment]
Example: 0xFF394149

The first two bytes mark **transparency** (from 00 to FF), here FF (which means text will be fully opaque.)
The remaning six bytes are for the **color code** itself, here 494139.
You might say: but the color code is different from the color byte! It was 394149 and the actual color code is 494139. This is because this is a **little endian** value: bytes are reversed. So instead of having **49** 41 _39_, you reverse the byte order and you now have _39_ 41 **49**.
